name: Terraform S3 Bucket Creation

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.5"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
	  role-to-assume: arn:aws:iam::664418970006:role/GitHubOIDCRole
          aws-region: ${{ secrets.AWS_REGION }}  # Make sure AWS region is passed here

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve




